[package]
name = "schmergles"
version = "0.1.0"
edition = "2021"
authors = ["Lukas Jonathan Gutschmidt <lg@lugut.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getopts = "0.2"
